config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'tweets#index'

  get '/users/sign_in', to: 'users#log_in'
  put '/users/sign_in', to: 'users#sign_in'
  put '/users/sign_up', to: 'users#sign_up'
  delete '/users/log_out', to: 'users#log_out'

  resources :tweets
  resources :users 

  resources :users, only: %i[show] do
    resources :followings, only: %i[create]
  end

  resources :followings, only: %i[destroy]

  resources :tweets, only: [:index, :create] do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates :content, presence: true
    belongs_to :user
    belongs_to :tweet
end
  

app/models/following.rb
class Following < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness: { scope: :tweet_id }
  belongs_to :user
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :text, presence: true
  belongs_to :author, class_name: 'User'
  has_many :likes
  has_many :comments, dependent: :destroy
  scope :ordered_by_most_recent, -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true, length: { maximum: 20 }
  validates :fullname, presence: true

  has_many :likes

  has_many :comments, dependent: :destroy

  has_many :authored_tweets, foreign_key: 'author_id', class_name: 'Tweet'

  has_many :active_followings, class_name: 'Following', foreign_key: :follower_id, dependent: :destroy
  has_many :followings, through: :active_followings, source: :followed

  has_many :passive_followings, class_name: 'Following', foreign_key: :followed_id, dependent: :destroy
  has_many :followers, through: :passive_followings, source: :follower

  scope :ordered_by_most_recent, -> { order(created_at: :desc) }

  mount_uploader :photo, PhotoUploader
  mount_uploader :cover_image, CoverImageUploader

  def follow(other_user)
    active_followings.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_followings.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    followings.include?(other_user)
  end

  def followings_posts
    followings_ids = followings.map(&:id)
    followings_ids << id
    Tweet.all.ordered_by_most_recent.where(author_id: followings_ids)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
      @comment = Comment.new(comment_params)
      @comment.tweet_id = params[:tweet_id]
      @comment.user = current_user
  
      if @comment.save
        redirect_to root_path, notice: 'Comment was successfully created.'
      else
        redirect_to root_path, alert: @comment.errors.full_messages.join('. ').to_s
      end
    end
  
    private
  
    def comment_params
      params.require(:comment).permit(:content)
    end
 end
  

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    current_user.follow(@user)

    redirect_to root_path
  end

  def destroy
    user = User.find(params[:id])
    current_user.unfollow(user)

    redirect_to root_path
  end

  def current_user
    User.find(session[:id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = User.find(session[:id]).likes.new(tweet_id: params[:tweet_id])

    redirect_to root_path if @like.save
  end

  def destroy
    like = Like.find_by(id: params[:id], user: User.find(session[:id]), tweet_id: params[:tweet_id])
    like.destroy
    redirect_to root_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all.ordered_by_most_recent
    @users = User.all.ordered_by_most_recent
    @tweet = Tweet.new
  end

  def new
    @tweet = User.find(session[:id]).tweets.build
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def create
    @tweet = User.find(session[:id]).authored_tweets.build(tweet_params)
    if @tweet.save
      redirect_to root_path, notice: 'Tweet successfully created'
    end
  end

  def edit 
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to root_path, notice: "Tweet updated"
    else
      render :edit
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy

    redirect_to root_path
  end

  private

  def tweet_params
    params.require(:tweet).permit(:text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:id] = @user.id
      session[:username] = @user.username
      redirect_to root_path, notice: 'You have successfully signed up'
    else
      render :new, alert: 'username has alraedy been taken'
    end
  end

  def show
    @user = User.find(params[:id])
    @personal_tweets = @user.authored_tweets.order('created_at DESC')
  end

  def sign_in
    @user = User.find_by(username: params[:username])

    if @user
      session[:id] = @user.id
      session[:username] = @user.username
      redirect_to root_path, notice: 'You have successfully signed in'
    else
      render :log_in, alert: "Username does not exist"
    end
  end

  # display log in form
  def log_in; end

  def log_out
    session.delete(:id)
    session.delete(:username)
    session.delete(:fullname)
    redirect_to users_sign_in_path, notice: 'You have successfully logged out'
  end

  private

  def user_params
    params.require(:user).permit(:username, :fullname, :photo, :cover_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatar_helper.rb
module AvatarHelper
  def avatar_for(user)
    encoded_name = ERB::Util.url_encode(user.fullname)
    src = "https://ui-avatars.com/api/?name=#{encoded_name}&format=svg&background=DBEAFE"

    content_tag(:img, '', src: src, alt: user.fullname, class: 'rounded-circle')
  end
end

app/helpers/following_helper.rb
module FollowingHelper
  def follow_button(user)
    return if current_user == user

    if !current_user.followings.exists?(user.id)
      form_with url: user_followings_path(user), method: :post do |form|
        form.submit 'Follow', class: " px-4 py-1 bg-primary text-light rounded-pill text-red-500 border
          border-red-500 rounded-full "
      end
    else
      form_with url: following_path(user), method: :delete do |form|
        form.submit 'Unfollow', class: " px-4 py-1 bg-danger text-light rounded-pill text-red-500 border
          border-red-500 rounded-full "
      end
    end
  end
end

app/helpers/like_helper.rb
module LikeHelper
  def like_btn(tweet)
    like = Like.find_by(tweet: tweet, user: current_user)
    if like
      link_to('Dislike!', tweet_like_path(id: like.id, tweet_id: tweet.id), method: :delete)
    else
      link_to('Like!', tweet_likes_path(tweet_id: tweet.id), method: :post)
    end
  end
end

app/helpers/user_helper.rb
module UserHelper
  def user_signed_in?
    session[:id] ? true : false
  end

  def current_user
    User.find(session[:id])
  end
end

app/views/comments/_comments.html.erb
<div class="post-comments">
  <p>
    <b><%= comment.user.fullname %>:</b><%= comment.content %>
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Africa Facts Zone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="title" property="og:title" content="Africa Facts Zone">
<meta property="og:type" content="website">
<meta name="image" property="og:image" content="https://github.com/ZawadiSumba66/twitter-redesign/raw/development/app/assets/images/screenshot2.jpeg">
<meta name="description" property="og:description" content="A desktop application where signed in users can tweet anything about Africa ranging from historic and political events, African heritage, natural features etc. ">
<meta name="author" content="Rose Sumba">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
     <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
     <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Redressed&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"/>
  </head>

  <body>
    <%if flash[:notice]%>
      <div class = "alert-success alert_wrapper"><%= flash[:notice] %></div>
    <%elsif flash.now[:alert]%>
      <div class = "alert-error alert_wrapper"><%= flash[:alert] %></div>
    <%end%>
    <%= yield %>
  </body>
</html>

app/views/tweets/_feed.html.erb
<% @tweets.includes(:author, :likes).each do |tweet|%>
       <div class="d-flex justify-content-between pr-3 pb-3 profile-feed">
        <div>
        <img src="<%=tweet.author.photo unless tweet.author.blank?%>" class="rounded-circle"/>
        <span class='font-weight-bold text-primary pl-3 '><%=tweet.author.fullname unless tweet.author.blank?%><%= '@' + tweet.author.username unless tweet.author.blank?%></span>
        </div>
        <p><%= tweet.created_at.strftime("#{tweet.created_at.day.ordinalize} %B %Y %l:%M%P")%></p>
       </div>
        <p><%= tweet.text%></p>
      <div class>
        <div>
          <%=like_btn(tweet)%>
          <%=tweet.likes.count%>
        </div>
      </div>
        <hr class="my-4">
<%end%>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
    <ul>
       <% @tweet.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
       <% end %>
    </ul>
    <%= f.text_area :text, class: "form-control h-50 border-rounded", placeholder: "Let's Tweet Africa"%>
    <br>
    <%= f.button :Tweet,  class: "btn btn-primary d-flex justify-content-end" %>
<% end %>

app/views/tweets/_homepage.html.erb
<div class="d-flex row no-gutters">
<div class="col-2">
<%=render 'left_nav'%>
</div>
<div class="lower_side col-10">
    <%= render'top_nav'%>
   <div class="d-flex">
   <div class="col-8">
	<div class="tweet-form bg-white rounded-md shadow px-5 py-2">
	   <%=render 'tweet_form'%>
    </div>
	<div class="tweet_feed text-dark bg-white rounded-md shadow mt-5 pl-4">
	   <%=render 'feed'%>
	</div>
	</div>
	<div class="follow w-50 mx-auto  col-4  rounded-md shadow pl-4 ">
	   <%=render 'who_to_follow'%>
    </div>
	</div>
</div>
</div>

app/views/tweets/_left_nav.html.erb
<div class="left text-secondary  px-2 pt-3">
      <div class="d-flex text-center">
       <div class="profile-users">
         <img src="<%=current_user.photo%>" class="rounded-circle"/>
		</div>
		<div class="profile-name pt-4 pl-3">
		  <%=current_user.fullname%>
		</div>
		</div>
		<div class="d-flex pt-4">
		 <div class="px-3 text-center">
		                <p class="tweets text-light font-weight-bold"><%=current_user.followers.count%></p>
                        <p class="heading">Followers</p>
                    </div>
                    <div class="px-3 text-center">
					  <p class="title is-6 text-light font-weight-bold"><%=current_user.followings.count%></p>
                        <p class="heading">Followings</p>
                    </div>
					</div>
		  <strong class="pr-3"><i class="fas fa-home"></i><%= link_to 'Homepage', root_path, class: "text-light"%></strong><br />
		  <br>
	      <strong class="pr-3"><i class="fas fa-user"></i><%= link_to 'Profile', current_user, class: "text-light"%></strong><br />
</div>

app/views/tweets/_navbar.html.erb
<div class= " row d-flex">
<div class="left text-secondary col-2 pl-4 ">
		<p class="panel-heading">Profile</p>
						<p class="names">
							<strong><%= current_user.username %></strong><br />
							<small><%= current_user.fullname %></small>
						</p>
                <div class="followings d-flex">
				<div class="level-item">
					<div>
						<p class="heading">Following</p>
						<p class="title is-6">123</p>
					</div>
				</div>
					<div class="level-item">
					<div>
						<p class="heading">Followers</p>
						<p class="title is-6">465K</p>
					</div>
				</div>
                </div>
</div>
<div class="top_nav text-light col-10 ">
<div class="d-flex justify-content-between pt-3">
   <div class="logo">
    <p>African Digest</p>
	</div>
   <div class="names d-flex">
	  <strong class="text-gray pr-3"><%= current_user.username %></strong><br />
	  <strong class="text-gray pr-5"><%= link_to 'Log out' %></strong>
	</div>
	</div>
</div>
</div>

app/views/tweets/_top_nav.html.erb
<div class="top_nav d-flex justify-content-between">
    <p class="pt-2"><%= link_to link_to 'AfricaFactsZone', root_path, class: "logo pl-3 text-light" %></p>
   <p class="names d-flex justify-content-end pt-4">
	  <strong ><%= link_to current_user.fullname, current_user, class: "text-light pr-3" %></strong><br />
	  <strong ><%= link_to 'Log out', users_log_out_path, class: "text-light pr-4", method: :delete %></strong>
	</p>
</div>

app/views/tweets/_tweet_form.html.erb
<div class="fill_form mt-4">
<div class="tweet_header text-dark d-flex">
   <%=link_to 'Tweet', root_path, class: "text-dark pr-3 pb-3 text-decoration-none border-bottom-2" %>
</div>
<%=render 'form', tweet: @tweet%>
</div>

app/views/tweets/_welcome.html.erb
<div class=" mx-auto w-50 pt-5 mt-5 col-12">
<div class="logo text-primary">
  <p class="d-flex justify-content-center"> Welcome to Africa Facts Zone</p>
 </div>
 <div>
 <div class="text-center pb-5">
<%= link_to 'Register',new_user_path, class: "btn btn-primary font-weight-bold"%>
<%= link_to 'Sign in',users_sign_in_path ,class: "btn btn-primary font-weight-bold" %>
</div>
 <div class="welcome">
<%=  image_tag("africa.jpg", :alt => "profile_image", class: "w-100 h-60") %>
</div>
</div>
</div>

app/views/tweets/_who_to_follow.html.erb
      <p class="pt-2 font-weight-bold text-secondary ">Who to follow</p>
            <%@users.each do |user|%>
            <% unless current_user==user%>
               <div class="d-flex justify-content-center">
               <div class="profile-follow">
                 <img src="<%=user.photo%>" class="rounded-circle"/>
                </div>
               <div class="col-6">
                 <strong><%=link_to user.username, user_path(user)%></strong>
                  <br>
                 <small><%= user.fullname %></small>
                 </div>
                 <div class="col-6">
                 <%= follow_button(user) %>
                 </div>
               </div>
                <hr>
              <%end%>
              <%end%>

app/views/tweets/edit.html.erb
<div class="fill_form mt-4">
<div class="tweet_header text-dark d-flex">
   <%=link_to 'Update your tweet', edit_tweet_path, class: "text-dark pr-3 pb-3 text-decoration-none border-bottom-2" %>
</div>
<%=render 'form', tweet: @tweet%>
</div>

app/views/tweets/index.html.erb
        <%if user_signed_in?%>
           <%= render 'homepage'%>
         <%else%>
            <%=render 'welcome'%>
        <%end%>

app/views/users/log_in.html.erb
<div class=" mx-auto w-50 pt-5 mt-5 col-12">
<div class="logo text-primary">
  <p class="d-flex justify-content-center">Africa Facts Zone</p>
 </div>
<h1 class="text-primary">Sign In</h1>

 <%= form_with model: @user, method: "put" do |form|%>
      <%= form.text_field :username, class: 'form-control', placeholder: "Enter your username"%>
      <br>
      <br>
      <%= form.submit "Log in", class: " btn btn-primary"%>
    <% end %>
    <p>Don't have an account? </p>
<%= link_to 'Sign up',new_user_path %>
</div>

app/views/users/new.html.erb
<div class="section  mx-auto w-50 pt-5 mt-5 col-12">
<div class="container">
<div class="logo text-primary">
  <p class="d-flex justify-content-center">Africa Facts Zone</p>
 </div>
<h1 class="text-primary">Sign Up</h1>
<br>
<%= form_with model: @user do |form| %>
    <%= form.text_field :username, placeholder: "Enter your Username", class: 'form-control'%>
    <br>
    <br>
     <%= form.text_field :fullname, placeholder: "Enter your Fullname", class: 'form-control'%>
    <br />
     <%= form.label :photo, "Choose your profile image"%>
     <br />
     <%= form.file_field :photo, label: "Enter your Fullname"%>
     <br />
     <br />
      <%= form.label :cover_image, "Choose your cover image"%>
       <br />
     <%= form.file_field :cover_image%>
    <br/>
    <br/>
    <%= form.submit "Sign up", class: "btn-primary  btn"%>
<% end %>
<p>Already have an account? </p>
<%= link_to 'Sign in',users_sign_in_path %>
</div>
</div>

app/views/users/show.html.erb
<div class="d-flex row no-gutters">
<div class="left_side col-2">
<%=render 'tweets/left_nav'%>
</div>
<div class="lower_side col-10">
    <%=render 'tweets/top_nav'%>
   <div class="d-flex row no-gutters">
   <div class="col-8 ">
	<div class="top_image mr-3">
      <img src="<%=@user.cover_image%>" class="w-100"/>
      </div>
	<div class="personal_tweets bg-white rounded-md shadow mx-3 pl-5 pb-3 mt-3">
     <%if @personal_tweets.blank?%>
        <h5 class="text-center font-weight-bold">No Tweets available ___</h5>
        <p><%= link_to 'Tweet now', root_path, class: 'px-4 py-1 bg-primary text-light rounded-pill text-red-500 border
          border-red-500 rounded-full'%></p>
     <%else%>
     <%@personal_tweets.each do |personal|%>
     <div class="d-flex justify-content-between pr-4">
       <p><%= personal.text%></p>
       <p><%= personal.created_at.strftime("#{personal.created_at.day.ordinalize} %B %Y %l:%M%P") %></p>
       </div><br>
        <%= link_to 'edit', edit_tweet_path(personal) %> |
        <%= link_to "delete", tweet_path(personal),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %>
        <hr>
     <%end%>
     <%end%>
    </div>
	</div>
	<div class="col-4 profile-users text-center">
            <p class="panel-heading">Profile</p>
                        <img src="<%=@user.photo%>" class="rounded-circle"/>
                        <p class="names">
                            <strong><%= @user.username %></strong><br />
                            <small><%= @user.fullname %></small>
                        </p>
                <div class="followings ">
                <div class="level-item d-flex justify-content-center">
                    <div class="px-3">
                        <p class="heading">Tweets</p>
                         <p class="tweets"><%=@user.authored_tweets.count%></p>
                    </div>
                    <div class="px-3">
                        <p class="heading">Followings</p>
                        <p class="title is-6"><%=@user.followings.count%></p>
                    </div>
                    <div class="level-item">
                    <div>
                        <p class="heading">Followers</p>
                        <p class="title is-6"><%=@user.followers.count%></p>
                    </div>
                </div>
                </div>
				<div>
				  <%= follow_button(@user)%>
				</div>
				 <div>
                    <p class="heading">Followed by</p>
                    <%@user.followers.each do |follower|%>
                       <%= follower.fullname%>
                    <%end%>
                </div>
    </div>
	</div>
</div>
</div>